In [1]:
import pandas as pd
import mysql.connector
import os

In [5]:
BASE_PATH = r"C:\Users\KIIT0001\OneDrive\Desktop\attendence_project\data\raw"
PROCESSED_PATH = r"C:\Users\KIIT0001\OneDrive\Desktop\attendence_project\data\processed"

# Create processed folder if not exists
os.makedirs(PROCESSED_PATH, exist_ok=True)

In [6]:
students = pd.read_csv(f"{BASE_PATH}/student_details.csv")
students

,student_id,roll_number,full_name,email,department,semester,created_at
0,100,23051128,Aarav Verma,23051128@college.edu,EEE,2,2026-04-16 16:13:15
1,131,23077660,Yash Verma,23077660@college.edu,ECE,2,2026-04-16 16:13:15
2,142,23078954,Mohit Reddy,23078954@college.edu,ME,7,2026-04-16 16:13:15
3,155,23074104,Ananya Mehta,23074104@college.edu,IT,7,2026-04-16 16:13:15
4,158,23069482,Meera Das,23069482@college.edu,CSE,1,2026-04-16 16:13:15
...,...,...,...,...,...,...,...
9995,49969,23074583,Yash Sharma,23074583@college.edu,EEE,3,2026-04-16 16:13:15
9996,49975,23058580,Priya Dubey,23058580@college.edu,IT,1,2026-04-16 16:13:15
9997,49986,23071815,Diya Ghosh,23071815@college.edu,ME,1,2026-04-16 16:13:15
9998,49991,23053061,Aarav Gupta,23053061@college.edu,ECE,2,2026-04-16 16:13:15
9999,49998,23052491,Sai Iyer,23052491@college.edu,CSE,6,2026-04-16 16:13:15

In [7]:
courses = pd.read_csv(f"{BASE_PATH}/course_details.csv")
courses

    course_id course_code               course_name  faculty_id  credits
0         513       ME443    Industrial Engineering          34        4
1         531       ME412         Plant Engineering           5        2
2         559      CSE366     Software Architecture          20        3
3         573      EEE150   Electrical Measurements          16        2
4         575      ECE458       IoT Hardware Design          22        3
..        ...         ...                       ...         ...      ...
95       1951      CSE443          Game Development          25        4
96       1960      CSE354         Quantum Computing          41        3
97       1974      EEE422  Renewable Energy Systems          48        5
98       1984      CSE460               Data Mining          28        4
99       1987       IT360      Information Security           5        3

[100 rows x 5 columns]

In [8]:
faculties = pd.read_csv(f"{BASE_PATH}/faculty_details.csv")
faculties

,faculty_id,faculty_name,email,designation,created_at
0,1,Dr. Raj Mehta,raj.mehta@college.edu,Professor,2026-04-16 15:23:11
1,2,Dr. Anita Sharma,anita.sharma@college.edu,Associate Professor,2026-04-16 15:23:11
2,3,Dr. Karan Patel,karan.patel@college.edu,Assistant Professor,2026-04-16 15:23:11
3,4,Dr. Neha Verma,neha.verma@college.edu,Professor,2026-04-16 15:23:11
4,5,Dr. Suresh Iyer,suresh.iyer@college.edu,Associate Professor,2026-04-16 15:23:11
5,6,Dr. Priya Nair,priya.nair@college.edu,Assistant Professor,2026-04-16 15:23:11
6,7,Dr. Manish Gupta,manish.gupta@college.edu,Professor,2026-04-16 15:23:11
7,8,Dr. Ritu Malhotra,ritu.malhotra@college.edu,Assistant Professor,2026-04-16 15:23:11
8,9,Dr. Arvind Rao,arvind.rao@college.edu,Associate Professor,2026-04-16 15:23:11
9,10,Dr. Shalini Desai,shalini.desai@college.edu,Professor,2026-04-16 15:23:11
10,11,Dr. Vivek Khanna,vivek.khanna@college.edu,Assistant Professor,2026-04-16 15:23:11
11,12,Dr. Meera Joshi,meera.joshi@college.edu,Associate Professor,2026-04-16 15:23:11
12,13,Dr. Rohit Kulkarni,rohit.kulkarni@college.edu,Professor,2026-04-16 15:23:11
13,14,Dr. Anjali Menon,anjali.menon@college.edu,Assistant Professor,2026-04-16 15:23:11
14,15,Dr. Deepak Chawla,deepak.chawla@college.edu,Associate Professor,2026-04-16 15:23:11
15,16,Dr. Kavita Bansal,kavita.bansal@college.edu,Professor,2026-04-16 15:23:11
16,17,Dr. Nikhil Sinha,nikhil.sinha@college.edu,Assistant Professor,2026-04-16 15:23:11
17,18,Dr. Swati Gokhale,swati.gokhale@college.edu,Associate Professor,2026-04-16 15:23:11
18,19,Dr. Harish Vyas,harish.vyas@college.edu,Professor,2026-04-16 15:23:11
19,20,Dr. Pooja Reddy,pooja.reddy@college.edu,Assistant Professor,2026-04-16 15:23:11
20,21,Dr. Ajay Thakur,ajay.thakur@college.edu,Associate Professor,2026-04-16 15:23:11
21,22,Dr. Sneha Kulshreshtha,sneha.kulshreshtha@college.edu,Professor,2026-04-16 15:23:11
22,23,Dr. Mohan Krishnan,mohan.krishnan@college.edu,Assistant Professor,2026-04-16 15:23:11
23,24,Dr. Radhika Jain,radhika.jain@college.edu,Associate Professor,2026-04-16 15:23:11
24,25,Dr. Tarun Bhatia,tarun.bhatia@college.edu,Professor,2026-04-16 15:23:11
25,26,Dr. Sonal Kapoor,sonal.kapoor@college.edu,Assistant Professor,2026-04-16 15:23:11
26,27,Dr. Gaurav Saxena,gaurav.saxena@college.edu,Associate Professor,2026-04-16 15:23:11
27,28,Dr. Nisha Pillai,nisha.pillai@college.edu,Professor,2026-04-16 15:23:11
28,29,Dr. Varun Shetty,varun.shetty@college.edu,Assistant Professor,2026-04-16 15:23:11
29,30,Dr. Leena Mukherjee,leena.mukherjee@college.edu,Associate Professor,2026-04-16 15:23:11
30,31,Dr. Ashok Banerjee,ashok.banerjee@college.edu,Professor,2026-04-16 15:23:11
31,32,Dr. Divya Khatri,divya.khatri@college.edu,Assistant Professor,2026-04-16 15:23:11
32,33,Dr. Ramesh Pawar,ramesh.pawar@college.edu,Associate Professor,2026-04-16 15:23:11
33,34,Dr. Shreya Dutta,shreya.dutta@college.edu,Professor,2026-04-16 15:23:11
34,35,Dr. Hemant Shukla,hemant.shukla@college.edu,Assistant Professor,2026-04-16 15:23:11
35,36,Dr. Pallavi Sethi,pallavi.sethi@college.edu,Associate Professor,2026-04-16 15:23:11
36,37,Dr. Yogesh Deshpande,yogesh.deshpande@college.edu,Professor,2026-04-16 15:23:11
37,38,Dr. Charu Venkatesh,charu.venkatesh@college.edu,Assistant Professor,2026-04-16 15:23:11
38,39,Dr. Sanjay Narang,sanjay.narang@college.edu,Associate Professor,2026-04-16 15:23:11
39,40,Dr. Meenal Bhatt,meenal.bhatt@college.edu,Professor,2026-04-16 15:23:11
40,41,Dr. Keshav Tripathi,keshav.tripathi@college.edu,Assistant Professor,2026-04-16 15:23:11
41,42,Dr. Rupa Srinivasan,rupa.srinivasan@college.edu,Associate Professor,2026-04-16 15:23:11
42,43,Dr. Om Prakash,om.prakash@college.edu,Professor,2026-04-16 15:23:11
43,44,Dr. Tanvi Kohli,tanvi.kohli@college.edu,Assistant Professor,2026-04-16 15:23:11
44,45,Dr. Jatin Arora,jatin.arora@college.edu,Associate Professor,2026-04-16 15:23:11
45,46,Dr. Bhavna Saxena,bhavna.saxena@college.edu,Professor,2026-04-16 15:23:11
46,47,Dr. Kunal Wadhwa,kunal.wadhwa@college.edu,Assistant Professor,2026-04-16 15:23:11
47,48,Dr. Shruti Rao,shruti.rao@college.edu,Associate Professor,2026-04-16 15:23:11
48,49,Dr. Pradeep Malviya,pradeep.malviya@college.edu,Professor,2026-04-16 15:23:11
49,50,Dr. Aishwarya Nambiar,aishwarya.nambiar@college.edu,Assistant Professor,2026-04-16 15:23:11

In [9]:
mapping = pd.read_csv(f"{BASE_PATH}/student_course_map_details.csv")
mapping

       map_id  student_id  course_id
0      123234         100       1005
1      121106         100       1409
2      123476         142        584
3      124046         142       1184
4      128937         142       1778
...       ...         ...        ...
14995  133389       49986       1598
14996  128965       49991        901
14997  133646       49991       1787
14998  133908       49998       1830
14999  129724       49998       1951

[15000 rows x 3 columns]

In [10]:
attendance = pd.read_csv(f"{BASE_PATH}/attendance_details.csv")
attendance

,attendance_id,student_id,course_id,attendance_date,status,recorded_at
0,1,12648,1960,2026-03-01,Present,2026-04-18 17:23:03
1,2,25218,1670,2026-03-02,Absent,2026-04-18 17:23:03
2,3,42995,1496,2026-03-04,Present,2026-04-18 17:23:03
3,4,46889,575,2026-03-10,Present,2026-04-18 17:23:03
4,5,12673,858,2026-03-08,Present,2026-04-18 17:23:03
...,...,...,...,...,...,...
14995,14996,47755,1487,2026-03-03,Present,2026-04-18 17:23:03
14996,14997,13632,1913,2026-03-02,Present,2026-04-18 17:23:03
14997,14998,46154,1587,2026-03-03,Absent,2026-04-18 17:23:03
14998,14999,49539,1333,2026-03-08,Absent,2026-04-18 17:23:03
14999,15000,37471,998,2026-03-04,Present,2026-04-18 17:23:03

In [11]:
print("CSV Loaded Successfully")
students.head()

CSV Loaded Successfully

,student_id,roll_number,full_name,email,department,semester,created_at
0,100,23051128,Aarav Verma,23051128@college.edu,EEE,2,2026-04-16 16:13:15
1,131,23077660,Yash Verma,23077660@college.edu,ECE,2,2026-04-16 16:13:15
2,142,23078954,Mohit Reddy,23078954@college.edu,ME,7,2026-04-16 16:13:15
3,155,23074104,Ananya Mehta,23074104@college.edu,IT,7,2026-04-16 16:13:15
4,158,23069482,Meera Das,23069482@college.edu,CSE,1,2026-04-16 16:13:15

In [13]:
#Removing duplicate values
students = students.drop_duplicates()
courses = courses.drop_duplicates()
faculties = faculties.drop_duplicates()
mapping = mapping.drop_duplicates()
attendance = attendance.drop_duplicates()

In [14]:
# Convert date columns
students["created_at"] = pd.to_datetime(students["created_at"])
faculties["created_at"] = pd.to_datetime(faculties["created_at"])
attendance["attendance_date"] = pd.to_datetime(attendance["attendance_date"]).dt.date
attendance["recorded_at"] = pd.to_datetime(attendance["recorded_at"])

print("Data Cleaned Successfully")

Data Cleaned Successfully

In [15]:
students.to_csv(f"{PROCESSED_PATH}/clean_students.csv", index=False)
courses.to_csv(f"{PROCESSED_PATH}/clean_courses.csv", index=False)
faculties.to_csv(f"{PROCESSED_PATH}/clean_faculty.csv", index=False)
mapping.to_csv(f"{PROCESSED_PATH}/clean_mapping.csv", index=False)
attendance.to_csv(f"{PROCESSED_PATH}/clean_attendance.csv", index=False)

print("Processed CSV files saved successfully!")

Processed CSV files saved successfully!

In [16]:
os.listdir(PROCESSED_PATH)

['clean_attendance.csv',
 'clean_courses.csv',
 'clean_faculty.csv',
 'clean_mapping.csv',
 'clean_students.csv']

In [17]:
conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="1234",
    database="attendance_tracking_system"
)

cursor = conn.cursor()

In [18]:
# Faculty
cursor.executemany("""
INSERT IGNORE INTO faculty (faculty_id, faculty_name, email, designation, created_at)
VALUES (%s, %s, %s, %s, %s)
""",
faculties[["faculty_id", "faculty_name", "email", "designation", "created_at"]].values.tolist()
)

# Students
cursor.executemany("""
INSERT IGNORE INTO students (student_id, roll_number, full_name, email, department, semester, created_at)
VALUES (%s, %s, %s, %s, %s, %s, %s)
""",
students[["student_id", "roll_number", "full_name", "email", "department", "semester", "created_at"]].values.tolist()
)

# Courses
cursor.executemany("""
INSERT IGNORE INTO courses (course_id, course_code, course_name, faculty_id, credits)
VALUES (%s, %s, %s, %s, %s)
""",
courses[["course_id", "course_code", "course_name", "faculty_id", "credits"]].values.tolist()
)

# Mapping
cursor.executemany("""
INSERT IGNORE INTO student_course_map (student_id, course_id)
VALUES (%s, %s)
""",
mapping[["student_id", "course_id"]].values.tolist()
)

# Attendance
cursor.executemany("""
INSERT IGNORE INTO attendance (student_id, course_id, attendance_date, status, recorded_at)
VALUES (%s, %s, %s, %s, %s)
""",
attendance[["student_id", "course_id", "attendance_date", "status", "recorded_at"]].values.tolist()
)

conn.commit()
cursor.close()
conn.close()

print("Data inserted into MySQL successfully!")

Data inserted into MySQL successfully!

In [19]:
print("ETL COMPLETED SUCCESSFULLY")

ETL COMPLETED SUCCESSFULLY